### ISSUE TITLE
The Wiki isn't publicly editable, nor is it clear how to suggest changes to the Wiki.

### ISSUE THREAD

**Issue by Aquaticat** [run-z/run-z#49]
The GitHub Wiki is by default only editable by repository collabrators.

See https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis

I discovered this when I tried to edit the Wiki since I found some problems with it.

I understand that making GitHub Wiki publicly editable could be unwanted, and proposing changes to the Wiki by opening issues is cumbersome. Therefore, I suggest you close the GitHub wiki, and migrate its content to the Git repository.

**Comment by Aquaticat** [comment]
An example of the problems is in:

https://github.com/run-z/run-z/wiki/Reusing-package-selectors

> Just place an ellipsis before the name of the task containing selectors.
> The task should be a group task. This task may, in turn, reuse other selectors.

It's better to write what an ellipsis is just after describing it in language.
"an ellipsis" can mean different things in different languages.

> Just place an ellipsis (`...`) before the name of the task containing selectors.
> The task should be a group task. This task may, in turn, reuse other selectors.

This not only makes sure everyone is on the same page,
but also reduce the cognitive load on the reader.

**Comment by surol** [comment]
Note that after moving wiki articles to the repository, they should stay available via direct links from README file.
The latter is available in different places. E.g. in NPM repository. So, those links have to be absolute.

**Comment by Aquaticat** [comment]
You got it! I do have a litte bit of bad news, though. My furnance stopped working earlier so the initial 24 hour deadline cannot be met.
