### ISSUE TITLE
The API documentation site doesn't make it clear immediately that it is only an API documentation site.

### ISSUE THREAD

**Issue by Aquaticat** [run-z/run-z#50]
https://run-z.github.io/run-z/

If one is unfamiliar with [TypeDoc](https://typedoc.org/), this site could be easily mistaken as the main site, the API documentation site, and the Wiki all in one.

Proposal: Change the title to "API docs | run-z"

Didn't make a pull request for this because wasn't sure if this change is wanted.

Of course, if you change the site to the main site, and API documentation site, and the Wiki all in one, that is a better solution.

**Comment by surol** [comment]
Done

**Comment by Aquaticat** [comment]
It seems that another problem was introduced:

![API docs homepage](https://user-images.githubusercontent.com/66041952/148054842-6f875703-0022-43fa-873a-1e4bd31f7ab8.png)

Not sure why this is now on the API docs site, but it's clearly irrelevant. Can we do something about it?

**Comment by surol** [comment]
Aha. TypeDoc chooses wrong README automatically. Fixed.
