### ISSUE TITLE
English language version not provided for Russian blog post in readme

### ISSUE THREAD

**Issue by Aquaticat** [run-z/run-z#51]
The blog post https://habr.com/ru/post/517506/ in readme is in Russian, but an English version of it is not provided.

There are several possible resolutions:

1.  You could translate it to English yourself and provide that link alongside with it.

2.  You could put a link to [Building complex Node.js projects with the run-z utility / sudo null it news | Google Translate translated English version](https://habr-com.translate.goog/ru/post/517506/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en-US).

    Caution: This resolution could be seen as disrespecting viewers' privacy.
    (Cause the translation service is provided by Google.)
    This is the reason why I didn't make a pull request for this.

3.  I could try rewriting the translation provided by Google Translate to make it sound more natural,
    but I am not the author of the post (that's you!) nor do I trust Google Translate to be accurate.

**Comment by surol** [comment]
That is very problematic for me. I am a terrible writer, and publishing articles brings me nothing but frustration. Tried to force myself to publish something at https://dev.to few times already. Never happened.

**Comment by Aquaticat** [comment]
It's okay. I think this issue can be closed when [#53](https://github.com/run-z/run-z/issues/53) is done, since the whole motivation behind that issue is to provide examples, and your blog post merely provided some examples.

The readme in that (currently nonexistant) repo could fully replace that blog post by providing real world and immediately runnable examples.
