### ISSUE TITLE
Redundant `(npm)` annotations

### ISSUE THREAD

**Issue by Aquaticat** [run-z/run-z#52]
Consider the following snippet found in readme:

```
npm run all  # (npm)
pnpm all     # (pnpm)
yarn all     # (yarn)
```

It is immediately obvious from the command itself that which package manager is used for this command.

Adding `(npm)` everywhere merely adds to the visual noise. I suggest removing them.
Not sure if that would be a welcome change, so didn't make pull request.

In case you don't want to remove these annotations:

1.  `(` and `)` are necessary. Remove.

2.  `#`s are not aligned nor theh same distance from code.
    Either align them or make them so.

3.  Consider using stylistic spelling of the names:

    -   [npm](https://en.wikipedia.org/wiki/Npm_(software))

    -   [Yarn](https://en.wikipedia.org/wiki/Yarn_(package_manager))

    -   [PnPM](https://pnpm.io/)

    Refer to Wikipedia or their official website for their style of spelling.

**Comment by surol** [comment]
These comments denote alternatives. Without them, the code snippet looks like a series of commands to execute.

Maybe it is better to be more precise here by commenting like `# With npm` or `# With Yarn`

Funny thing about pnpm. Each time I reload their main page, the "pnpm" changes its name. Like "pnPm" or "pnpM".

**Comment by Aquaticat** [comment]
Alright. I didn't consider that.

What about this?

```xml
                <tabs group="languages">
                    <tab title="Gradle (Groovy)" group-key="groovy">
                        <code style="block" lang="Groovy" interpolate-variables="true">
                            dependencies {
                                implementation "io.ktor:ktor-server-core:%ktor_version%"
                                implementation "io.ktor:ktor-server-netty:%ktor_version%"
                                implementation "ch.qos.logback:logback-classic:%logback_version%"
                            }
                        </code>
                    </tab>
                    <tab title="Gradle (Kotlin)" group-key="kotlin">
                        <code style="block" lang="Kotlin" interpolate-variables="true">
                            dependencies {
                                implementation("io.ktor:ktor-server-core:%ktor_version%")
                                implementation("io.ktor:ktor-server-netty:%ktor_version%")
                                implementation("ch.qos.logback:logback-classic:%logback_version%")
                            }
                        </code>
                    </tab>
                </tabs>
```

This is [Ktor.io](https://ktor.io)'s solution. The exact code is from [their GitHub repo](https://github.com/ktorio/ktor-documentation/blob/main/topics/Gradle.xml).

Sure, it's more work, but it's easier to read when rendered.
Currently with GitHub markdown, this might be impossible to do, but I'm assuming there will be a web docs portal later on.

**Comment by Aquaticat** [comment]
About pnpm:

I didn't notice that...

In that case, I'd say using their logo's spelling style (all lowercase) would be better:

![image](https://user-images.githubusercontent.com/66041952/148021903-7cfbf806-d4b9-47cc-b09d-72d766bc1f37.png)

**Comment by surol** [comment]
Removed those comments in favor of separate code block per package manager.

**Comment by Aquaticat** [comment]
Yes!
