### ISSUE TITLE
Specify a Markdown styleguide for this project.

### ISSUE THREAD

**Issue by Aquaticat** [run-z/run-z#54]
I used [Google's Markdown style guide](https://google.github.io/styleguide/docguide/style.html) [when writing pull request #48](https://github.com/run-z/run-z/pull/48#issuecomment-1004573133).

However, this project doesn't specify a markdown styleguide.

This has caused [some false-positives with Codacy](https://app.codacy.com/gh/run-z/run-z/pullRequest?prid=8653933).

Unsure where to specify it so didn't open a pull request immediately.

Ideally I want to put it into `readme/development/styleguides/markdown/index.md` but that's too opinionated.

**Comment by surol** [comment]
The style used here is a [remark-style-recommended](https://www.npmjs.com/package/remark-preset-lint-recommended) with two custom modifications:

1. Do not require tab-size indentation for lists. As it should be safe nowadays: https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-list-item-indent#recommendation

2. Allow [shortcut reference links](https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-no-shortcut-reference-link). As it complies with GitHub defaults.

**Comment by Aquaticat** [comment]
Alright, but it's not specified anywhere explictly. It should be.

However, I just took a look into this styleguide. It seems to be very loose to me. This is at best a linter, and a very loose one at that.

I believe at least another serious styleguide (like Google's) is needed to properly enforce style.

Remark can be kept as a linter to check for common problems.

**Comment by surol** [comment]
What about [this preset](https://github.com/remarkjs/remark-lint/tree/main/packages/remark-preset-lint-markdown-style-guide)? It states that it follows [Markdown Style Guide](https://cirosantilli.com/markdown-style-guide/)

**Comment by Aquaticat** [comment]
Looks promising, will look into it and report back within 10 minutes.

**Comment by Aquaticat** [comment]
Alright, I don't have any major complaints about the preset itself.

However, it should still be stated that this project follows the [Markdown Style Guide by Ciro Santilli](https://cirosantilli.com/markdown-style-guide/) and this is just a linter.

**Comment by Aquaticat** [comment]
So where do you want to specify the styleguide?

**Comment by surol** [comment]
Not sure. Dedicated file maybe? Like `STYLE_GUIDE.md`. It could list styles for both TypeScript and Markdown.

I am going to update configuration and reformat all Markdown then.

**Comment by Aquaticat** [comment]
In my initial message in this issue I proposed a solution:

> Ideally I want to put it into `readme/development/styleguides/markdown/index.md` but that's too opinionated.

I think that is going to help when/if `run-z` gets its main website.

What do you think of that?

**Comment by Aquaticat** [comment]
Also that could

**Comment by Aquaticat** [comment]
Sorry, accidentally closed this issue while typing. Now I forgot what I was going to type...

**Comment by surol** [comment]
Well, ok. I would prefer to name a top-level directory as `docs/`. The Wiki entries could be moved there too.

**Comment by Aquaticat** [comment]
Yes. `docs/` is clear. Let's do that. Actually, I'll open a pull request for that in 24 hours, including the styleguide and the wiki.

**Comment by Aquaticat** [comment]
> Not sure. Dedicated file maybe? Like `STYLE_GUIDE.md`. It could list styles for both TypeScript and Markdown.
> 
> I am going to update configuration and reformat all Markdown then.

My execution of the Google Markdown styleguide was completely conforming to this styleguide, so you won't have to reformat those I added.

The Wiki would be migrated to `docs/` and I'll reformat those files by hand so that I can correct some problems with the language (not saying your English is poor, just saying sometimes it could be better to explain it in another way), so these would be conforming to this styleguide, too.

The only thing that would need reformat is the top level `readme.md` then.

**Comment by surol** [comment]
I have enabled [remark-preset-lint-markdown-style-guide](https://github.com/remarkjs/remark-lint/tree/main/packages/remark-preset-lint-markdown-style-guide) with several customizations:
- Max line length is 120 chars
- Other settings to conform to Prettier formatting

New `pnpm format` command executes Prettier to format all Markdown files.

**Comment by Aquaticat** [comment]
https://cirosantilli.com/markdown-style-guide/#option-wrap-inner-sentence

kinda conflicts with Prettier in my experience. Prettier always wants to make everything align on the right.

There are also other issues I've found with Prettier. Notably it removes spaces after list symbols (not sure). It was however very problematic.

In fact, I've put .md in `.prettierignore` myself. I'd just format by hand. Please reconsider.

**Comment by surol** [comment]
Well, I can disable a [prose wrap](https://prettier.io/docs/en/options.html#prose-wrap). Prettier won't touch long sentences then.

As for spaces in lists - it adds them unconditionally.

**Comment by Aquaticat** [comment]
Alright. I'll try it when I draft the pull request for migrating wiki into `docs/` and I'll report back about whether I'm satisfied with it.

**Comment by surol** [comment]
Style guide added. Linter and Prettier configured. Please, feel free to open new issues is anything goes wrong.
