### ISSUE TITLE
Why is `trim_trailing_whitespace` set to `false` for `*.md`?

### ISSUE THREAD

**Issue by Aquaticat** [run-z/run-z#55]
In `.editorconfig`,

```editorconfig
[*.md]
trim_trailing_whitespace = false
```

Why is this done?

**Comment by surol** [comment]
The whitespaces at the end of a line are meaningful in Markdown. In particular, two spaces create a [hard line break](https://spec.commonmark.org/0.30/#hard-line-break).

On the other hand, the [remark-lint-hard-break-spaces](https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-hard-break-spaces) prevents using more or less than two spaces.

**Comment by Aquaticat** [comment]
Oh! I forgot about that.

However, I don't think hard line breaks are useful in markdown. It's very rare and I normally just do `<br>` manually. The reason for preferring `<br>` instead of two spaces at the end of line is because `<br>` is much more discoverable.
If two spaces were used instead, then I would not know what is up until the document is compiled to HTML & rendered.

If it is enforceable, I suggest disallow spaces at the end of line.

**Comment by surol** [comment]
Didn't find an option for this in Remark. Prettier also respects double space in the end of the line (and removes any extra spaces).
Btw, a `\` sign can be used instead of double space or `<br>`.
Will remove the option. It seems WebStorm ignores it anyway.

**Comment by Aquaticat** [comment]
Thanks for the quick resolution (and the tip)!
