### ISSUE TITLE
Change "Build" to "Build@linux"

### ISSUE THREAD

**Issue by Aquaticat** [run-z/run-z#56]
Not opening pull request because I'm unsure if merely

1.  changing `.github/workflows/build.yml` to `.github/workflows/build@linux.yml`

2.  changing line 5 of `readme.md`

would break something.

**Comment by surol** [comment]
An intention is to have a reference "Build" (on Linux). And additional builds to check compatibility only.

**Comment by Aquaticat** [comment]
Alright. But  `.github/workflows/build.yml` says build@linux inside. You might want to change that or add a comment there.
