### ISSUE TITLE
Prettier reindenting `json` code blocks in `.md` files to 4 spaces.

### ISSUE THREAD

**Issue by Aquaticat** [run-z/run-z#62]
Found this out after changing Prettier `format` script in `package.json` to properly include all `.md` files in subdirectories.

Before:

```
    "format": "run-z +z --then prettier --write \"**.{json,md}\"",
```

After:

```
    "format": "run-z +z --then prettier --write \"**/*.{json,md}\"",
```

Before:

```json
{
  "scripts": {
    "test": "run-z +z jest",
    "z": "run-z +test/--runInBand"
  }
}
```

After:

```json
{
    "scripts": {
        "test": "run-z +z jest",
        "z": "run-z +test/--runInBand"
    }
}
```

Clearly, this is unwanted. Not submitting formatted files in pull request because of this issue.

**Comment by surol** [comment]
This is unavoidable due to https://github.com/prettier/prettier/issues/5378
It seems using Prettier for all files is not an option.

**Comment by Aquaticat** [comment]
@surol I don't think this issue can be closed in its current state. Either we should just let Prettier format `json` inside markdown that way or we should whitelist markdown from Prettier.

**Comment by Aquaticat** [comment]
Also, the npm script is not working properly. You should either fix it or remove it.

**Comment by surol** [comment]
There is no perfect solution for this. Prettier is better to have, sometimes. E.g. I had to reformat the README file with Prettier, as you requested. Still, it is clean that Prettier is not a good thing everywhere.

**Comment by Aquaticat** [comment]
So what solution do you propose?

**Comment by surol** [comment]
Leave it be. Just ignore Prettier.

**Comment by Aquaticat** [comment]
Just to confirm: Are you saying not using Prettier to format these markdown files is the solution?

**Comment by surol** [comment]
> Just to confirm: Are you saying not using Prettier to format these markdown files is the solution?

Yes, don't use Prettier for formatting. You were right about it. It brings more problems than solves.

**Comment by Aquaticat** [comment]
Alright. I'll update `.../styleguide/markdown.md` to make sure I know it's not to be used in the future. Also I'll update #61 to include language names in code blocks.

**Comment by Aquaticat** [comment]
How do you feel about removing that npm script? I feel like removing that script is the right decision.

**Comment by surol** [comment]
Alright, you can remove it. But don't remove the devDependency. It could be useful. Occasionally.
