### ISSUE TITLE
Problem with <https://github.com/run-z/run-z/wiki/Task-annexes>

### ISSUE THREAD

**Issue by Aquaticat** [run-z/run-z#65]
What does "It does the same as the task, except the task execution." mean?

What does

"Note that each task would only be executed once.
Still, it can be specified multiple times, each time with its own set of parameters and attributes."

mean?

Not sure what

"While the following command
yarn test lint +cmd:test,+lint
would execute lint in parallel to test:client and test:server."

is doing here.

**Comment by surol** [comment]
See no problem. Everything is explained in the documentation.
