### ISSUE TITLE
How to kill run-z process

### ISSUE THREAD

**Issue by Muromi-Rikka** [run-z/run-z#67]
Commands started with run-z are not terminated by ctrl+c

**Comment by surol** [comment]
Operating system?

**Comment by Muromi-Rikka** [comment]
@surol operating system use windows11 ,windows terminal with powershell

**Comment by surol** [comment]
@Muromi-Rikka I have tried both PowerShell and cmd. Both terminate the process on Ctrl+C.
May be, this is related to some specific sub-process? Can you provide a small repro?

**Comment by Muromi-Rikka** [comment]
@surol I use pnpm workspace
root package.json
```json
{
  "scripts": {
    "all":"run-z serve:sunna,serve:lumina,watch:common",
    "serve:sunna": "pnpm --filter sunna start:dev",
    "serve:lumina": "pnpm --filter lumina start",
    "watch:common": "tsc --watch --project ./apps/common"
  },
  "devDependencies": {
    "@angular/cli": "^13.3.0",
    "@nestjs/cli": "^8.2.3",
    "run-z": "^1.10.0"
  }
}
```
lumina start:
```json
{"start": "ng serve"}
```
sunna start:
```json
{"start:dev": "nest start --watch"}
```

**Comment by surol** [comment]
I don't believe this is related to `run-z`.

The Ctrl+C (SIGINT) is sent to the whole process group. So, all of `lumina`, `sunna`, and `tsc` receive it. It's up to them to terminate properly. It seems that one of them fail to do so.

You can try `npm-run-all` and its `run-p` command instead. It seems you are not using `run-z` capabilities anyway.

**Comment by iki** [comment]
@surol  I have the same issue, `run-p` closes the running nodemon correctly, `run-z` leaves the process running (with server port open and working). On Windows 11 too. Would be great to fix it.

**Comment by Muromi-Rikka** [comment]
@iki try use google/wireit

**Comment by surol** [comment]
Version [1.10.1](https://github.com/run-z/run-z/releases/tag/v1.10.1) should fixe the issue. At least, it fixes it for [run-z/triage-sigint].

If the issue is still present for you, please help me find out the reason by providing a repro. E.g. by creating a PR for [run-z/triage-sigint].

[run-z/triage-sigint]: https://github.com/run-z/triage-sigint
